### ISSUE TITLE
Let's Encrypt automatic renewal is not renewing certificates

### ISSUE THREAD

**Issue by ironfroggy** [caktus/margarita#137]
- Cron job is in place, but certs are not renewed
- Possibly related to not updating LE before runnning renew command
- Affects all deployments using LE-provided certificates

**Comment by vkurup** [comment]
Just FYI, this is a different issue than the one affecting EpicAllies and Duckling. In those cases, LE properly updated the certs via the cron command, but nginx did not reload.

**Comment by vkurup** [comment]
We've improved the LetsEncrypt process in 2.2.0. Please re-open if you find new issues.
