### ISSUE TITLE
Migrations don't run with Django 1.10

### ISSUE THREAD

**Issue by kmtracey** [caktus/margarita#139]
Django 1.10 removes the migrate --list variant (showmigrations can be used instead). We use this here:

https://github.com/caktus/margarita/blob/develop/project/web/app.sls#L89

The effect on upgrading to Django 1.10 for existing projects seems to be migrations simply don't run.

**Comment by ironfroggy** [comment]
If we switch to `showmigrations` we'll break any projects running 1.7 or below, so we'll have to require 1.8 or newer to upgrade to a version of Margarita that fixes this. Will that be a problem for any projects stuck on 1.7 or lower?

**Comment by kmtracey** [comment]
I am questioning if we really need to "protect" running migrate by first checking if there is an un-applied migration. Other than possibly saving a tiny bit of time, why do we need to even check first. What harm would ensue if we just ran migrate every deploy?

**Comment by dpoirier** [comment]
I don't know any reason not to just run "migrate".

**Comment by kmtracey** [comment]
https://github.com/caktus/margarita/pull/140 removes the onlyif

**Comment by dpoirier** [comment]
It looks like this was fixed in #140, can we close #139?
