### ISSUE TITLE
failure to update let's encrypt repo

### ISSUE THREAD

**Issue by vrocha** [caktus/margarita#141]
ID: install_letsencrypt
Function: git.latest 
  Name: https://github.com/letsencrypt/letsencrypt/ 
Result: False
Comment: Repository would be updated to 387d61d, but this is not a fast-forward merge. Set 'force_reset' to True to force this update.

**Comment by dpoirier** [comment]
It looks like this is a problem that https://github.com/caktus/margarita/pull/134 should have fixed, but that was merged in June.  What version of Margarita did this problem happen on?  Has it been retried on the latest version?

**Comment by vkurup** [comment]
@vrocha we just updated Margarita to 2.2.0 with much more robust support for LetsEncrypt (i.e. not using a git checkout), and it should be completely backwards compatible. I'm going to close this, but please let me know if you run into issues.
