### ISSUE TITLE
Improve the Let's Encrypt process

### ISSUE THREAD

**Issue by jbradberry** [caktus/margarita#145]
It's about time we start doing this in a way that isn't so fragile.

- pip install certbot (the new name for the letsencrypt automated cert script)
- clean up the old git checkout of letsencrypt
- remove the old renewal cron job
- add a new cron job that executes `certbot-auto renew`, instead of having to match all of the subdomains and webroots used in the initial invocation
- use whichever nginx reload/restart command that won't silently fail

**Comment by vkurup** [comment]
Thanks @jbradberry. This work is now included in release 2.2.0.
