### ISSUE TITLE
UnicodeEncodeError when serving media with non-ascii filename

### ISSUE THREAD

**Issue by calebsmith** [caktus/margarita#29]
When requesting a media file in a URL such as: /media/avatars/csmith/resized/210/자연나라.jpg

The server returns a 500 and the following exception is shown in the traceback:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 61-64: ordinal not in range(128)

This occurs with gunicorn + supervisor when supervisor doesn't have it's locale set to en_utf8, (defaults to C)

**Comment by mlavin** [comment]
I looks like this has been addressed and can be closed.
