### ISSUE TITLE
Start versioning margarita

### ISSUE THREAD

**Issue by dpoirier** [caktus/margarita#44]
I'd like to start creating tagged releases for margarita, following our typical workflow, with most work occurring off a develop branch and creating a new release number when we merge changes to master. We can also add release notes or a change log indicating what's new in each "release".

Releases can of course occur frequently, even with every fix if we choose. Version numbers are cheap.

That will make it easier to keep our projects' deploys from breaking when margarita changes. We can pin our project to a particular release of margarita, and when we need some fix that's been added, update our pinned version and review the release notes to see what we might need to update in our project due to other margarita changes that might have happened. But if we don't need a fix, we can just keep using the version of margarita that is working for the project.

We could of course just pin to commit hashes and review the commit log when we update, but I'd prefer making this a more formal process. If nothing else, it'll help us remember that every change to margarita has the potential to cause problems and wasted time for multiple projects that use margarita.

**Comment by mlavin** [comment]
Yes :100: The base/branch can be configured per remote as of Salt 2014.7 http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#per-remote-configuration-parameters instead of always using the minion environment setting.

**Comment by dpoirier** [comment]
FYI, when I tried using gitfs with a specific branch, I never could get it to work. It never checked out any files at all, and there were no errors in the Salt-master log.

**Comment by mlavin** [comment]
Could you share the configuration which wasn't working?

**Comment by dpoirier** [comment]
It would have been something like this (based on http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#per-remote-configuration-parameters):

    fileserver_backend:
      - roots
      - git

    file_roots:
      base:
        - /srv/salt

    gitfs_remotes:
      - https://github.com/caktus/margarita.git:
        - base: 1.0.0

**Comment by mlavin** [comment]
@Scottm-Caktus had this working for a project. Any thoughts?
