### ISSUE TITLE
Move Salt states from django-project-template to Margarita

### ISSUE THREAD

**Issue by dpoirier** [caktus/margarita#55]
I propose moving ALL the Salt states (not pillar files) from django-project-template to Margarita.

* Existing projects will not be affected, since their own copies of the states will take precedence over those in Margarita.
* New projects will be able to take advantage of improvements in the states as they are added to margarita and the projects choose to use the newer version.  And they can still add custom states or copy and modify the states from Margarita if they have to (though hopefully they'll make improvements in Margarita so we can all benefit).

**Comment by mlavin** [comment]
Yes please :sparkles:

**Comment by dpoirier** [comment]
Fixed by #56.
