### ISSUE TITLE
Allow for removal of user accounts

### ISSUE THREAD

**Issue by vkurup** [caktus/margarita#66]
See caktus/django-project-template#115.

Maybe allow the addition of a ` - state: removed` parameter to the devs.sls file. If present, our code would remove the user instead of adding.

**Comment by dpoirier** [comment]
I suggest `state: absent` for consistency with the naming of the corresponding Salt state.

**Comment by dpoirier** [comment]
Something we could do right now when a developer leaves a project is just change their public key in `devs.sls` to something like 'DISABLED', so their real public key gets removed from the server on the next deploy.  (Unless Salt validates that the public key has the right syntax.)

**Comment by vkurup** [comment]
This has been fixed by #113 and #118. The approach chosen was to disable the SSH keys of any users who were not in devs.sls.
