### ISSUE TITLE
Missing newrelic_webmon state

### ISSUE THREAD

**Issue by copelco** [caktus/margarita#80]
The django-project-template references [project.newrelic_webmon](https://github.com/caktus/django-project-template/blob/master/conf/salt/top.sls#L19), but I can't seem to find that file. Should it be in margarita somewhere?

**Comment by vkurup** [comment]
I think that's an oversight from #58. The `project.newrelic_webmon` state shouldn't be needed anymore. All that is required is that `newrelic` is added to the production requirements and the license key added to the secrets. All other configuration can be done via env vars in the pillar, as described here: https://github.com/caktus/margarita#new-relic

So, I think the right fix is to remove the state from the project template, and perhaps make the docs a little clearer?

**Comment by dpoirier** [comment]
I opened this pull request against the project template to fix this: https://github.com/caktus/django-project-template/issues/216

**Comment by dpoirier** [comment]
Fixed by https://github.com/caktus/django-project-template/pull/216\
