### ISSUE TITLE
New relic and dotenv

### ISSUE THREAD

**Issue by copelco** [caktus/margarita#81]
Using the latest version of the template and margarita, I've had trouble getting the newrelic python agent functioning properly. After some debugging today, I believe the new relic environment variables are loaded too late for ``newrelic-admin`` to see them. Specifically, even though the [wsgi file](https://github.com/caktus/django-project-template/blob/master/project_name/wsgi.py#L14-L16) loads the environment variables:

```python
from . import load_env
load_env.load_env()
```

My hunch is that the ``load_env()`` command isn't executed in time for the ``newrelic-admin run-program`` wrapper script to catch the enivonment variables [here](https://github.com/caktus/margarita/blob/develop/project/web/gunicorn.conf#L2):

```ini
command={% if use_newrelic %}{{ virtualenv_root }}/bin/newrelic-admin run-program {% endif %}{{ virtualenv_root }}/bin/gunicorn {{ pillar['project_name'] }}.wsgi:application --bind=0.0.0.0:8000 --workers={{ grains['num_cpus'] * 2 + 1 }}
```

To test, if I export ``NEW_RELIC_LICENSE_KEY``, ``NEW_RELIC_LOG``, and ``NEW_RELIC_APP_NAME`` and then run the above supervisor command manually, New Relic starts reporting as expected.

Has anyone else run into this issue?

**Comment by dpoirier** [comment]
That would certainly make sense.  It would be nice if we had a wrapper script that would load from .env and then run a command in that context. django-dotenv doesn't come with one, but we could probably whip one up pretty easily and submit a pull request.
